'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useParams } from 'next/navigation';
import { io } from 'socket.io-client';
import { DisplayEnvelopeSchema, type DisplayScene } from '@watch-bracket/display-protocol';
import { RoomDisplay } from '@watch-bracket/display-ui';
import { RoomSnapshotSchema, ServerEnvelopeSchema } from '@watch-bracket/realtime-protocol';
import { api } from '../../../lib/api';
import { BrandLogo } from '../../../components/brand-logo';

function sceneFromSnapshot(value: unknown): DisplayScene {
  const snapshot=RoomSnapshotSchema.parse(value);
  if(snapshot.state==='LOBBY'||snapshot.state==='EXPIRED')return{type:'LOBBY',roomName:snapshot.name,roomCode:snapshot.code,joinUrl:`${window.location.origin}/join/${snapshot.code}`,locked:snapshot.locked,participants:snapshot.participants.map(({nickname,role,connected})=>({nickname,role,connected}))};
  if(snapshot.state==='NOMINATING'||snapshot.state==='NOMINATIONS_LOCKED')return{type:'NOMINATION_PROGRESS',roomName:snapshot.name,roomCode:snapshot.code,deadline:snapshot.nominationDeadline,submittedParticipants:snapshot.nominationProgress.submittedParticipants,lockedParticipants:snapshot.nominationProgress.lockedParticipants,totalParticipants:snapshot.nominationProgress.totalParticipants,revealed:snapshot.nominationsRevealed,candidates:snapshot.candidates.map(({title,mediaType,releaseYear,supportCount})=>({title,mediaType,releaseYear,supportCount}))};
  const tournament=snapshot.tournament;if(!tournament)throw new Error('Tournament unavailable');const matchup=tournament.activeMatchup;const candidate=(item:NonNullable<typeof matchup>['candidateA'])=>({id:item.id,title:item.title,mediaType:item.mediaType,releaseYear:item.releaseYear,runtimeMinutes:item.runtimeMinutes,contentRating:item.contentRating,genres:item.genres,seed:item.seed,strikes:item.strikes,redemption:item.redemption});if(snapshot.state==='WINNER'&&tournament.champion)return{type:'WINNER',roomName:snapshot.name,winner:candidate(tournament.champion),path:tournament.bracket.filter((result)=>result.winnerId===tournament.champion!.id).map((result)=>({stage:result.stage,opponentTitle:result.loserTitle}))};if(!matchup)throw new Error('Matchup unavailable');const base={roomName:snapshot.name,stage:matchup.stage,matchupNumber:matchup.sequence,totalMatchups:tournament.totalMatchups,candidateA:candidate(matchup.candidateA),candidateB:candidate(matchup.candidateB)};if(matchup.status==='INTRO')return{type:'MATCHUP_INTRO',...base,deadline:matchup.deadline};if(matchup.status==='VOTING')return{type:'MATCHUP_VOTING',...base,deadline:matchup.deadline!,votesReceived:matchup.votesReceived,eligibleVoters:matchup.eligibleVoters};const result=matchup.resolution!;const winner=result.winnerId===matchup.candidateA.id?matchup.candidateA:matchup.candidateB;const loser=result.loserId===matchup.candidateA.id?matchup.candidateA:matchup.candidateB;const winnerIsA=winner.id===matchup.candidateA.id;return{type:'MATCHUP_RESULT',roomName:snapshot.name,stage:matchup.stage,matchupNumber:matchup.sequence,totalMatchups:tournament.totalMatchups,winner:candidate(winner),loser:candidate(loser),votesWinner:winnerIsA?result.votesA:result.votesB,votesLoser:winnerIsA?result.votesB:result.votesA,abstentions:result.abstentions,tieBreak:result.tieBreak,deadline:matchup.deadline};
}
export default function ActiveDisplay(){const{displaySessionId}=useParams<{displaySessionId:string}>();const[scene,setScene]=useState<DisplayScene>();const[state,setState]=useState<'connected'|'reconnecting'|'revoked'>('reconnecting');const roomId=useRef('');const sequence=useRef(0);
  const load=useCallback(async()=>{const snapshot=RoomSnapshotSchema.parse(await api<unknown>(`/api/rooms/${roomId.current}/snapshot`));sequence.current=snapshot.sequence;setScene(sceneFromSnapshot(snapshot));},[]);
  useEffect(()=>{let socket:ReturnType<typeof io>|undefined;let disposed=false;void api<unknown>(`/api/displays/${displaySessionId}/snapshot`).then((value)=>{const snapshot=RoomSnapshotSchema.parse(value);if(disposed)return;roomId.current=snapshot.roomId;sequence.current=snapshot.sequence;setScene(sceneFromSnapshot(snapshot));socket=io({path:'/socket.io',withCredentials:true});socket.on('connect',()=>{setState('connected');socket!.emit('display:subscribe',{roomId:snapshot.roomId,displaySessionId});});socket.on('display:snapshot',(input:unknown)=>{const outer=ServerEnvelopeSchema.safeParse(input);if(!outer.success)return;const next=RoomSnapshotSchema.safeParse(outer.data.payload);if(!next.success)return;sequence.current=next.data.sequence;setScene(sceneFromSnapshot(next.data));});socket.on('display:scene',(input:unknown)=>{const parsed=DisplayEnvelopeSchema.safeParse(input);if(!parsed.success)return;if(sequence.current&&parsed.data.sequence>sequence.current+1){void load();return;}if(parsed.data.sequence>=sequence.current){sequence.current=parsed.data.sequence;setScene(parsed.data.scene);}});socket.on('display:revoked',()=>{setState('revoked');socket?.disconnect();});socket.on('disconnect',(reason)=>{if(reason!=='io client disconnect')setState('reconnecting');});}).catch(()=>setState('revoked'));return()=>{disposed=true;socket?.disconnect();};},[displaySessionId,load]);
  if(state==='revoked')return <RoomDisplay connection="revoked" scene={scene??{type:'LOBBY',roomName:'Display revoked',roomCode:'—',joinUrl:'https://bracket.famflix.live',locked:true,participants:[]}}/>;
  if(!scene)return <main className="display-connecting"><div><BrandLogo label="Shared display"/><h1>Connecting to the room…</h1><p>If this takes too long, pair the display again.</p></div></main>;
  return <RoomDisplay scene={scene} connection={state}/>;
}
