'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useParams } from 'next/navigation';
import { QRCodeSVG } from 'qrcode.react';
import { io, type Socket } from 'socket.io-client';
import { RoomSnapshotSchema, ServerEnvelopeSchema, type RoomSnapshot } from '@watch-bracket/realtime-protocol';
import { api } from '../../../lib/api';
import { useCast } from '../../../lib/use-cast';

const eventNames = ['room:snapshot','room:participant-joined','room:participant-left','room:participant-reconnected','room:locked','room:unlocked','display:paired','display:revoked'] as const;
export default function RoomPage() {
  const { roomId }=useParams<{roomId:string}>(); const [snapshot,setSnapshot]=useState<RoomSnapshot>(); const [connection,setConnection]=useState<'connecting'|'connected'|'reconnecting'>('connecting'); const [error,setError]=useState(''); const [pairingCode,setPairingCode]=useState(''); const sequence=useRef(0);
  const load=useCallback(async()=>{try{const value=await api<unknown>(`/api/rooms/${roomId}/snapshot`);const parsed=RoomSnapshotSchema.parse(value);sequence.current=parsed.sequence;setSnapshot(parsed);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load room');}},[roomId]);
  const castDisplay=snapshot?.displays.find((display)=>display.kind==='CAST');
  const cast=useCast({enabled:snapshot?.viewer==='HOST',roomId,activeDisplay:castDisplay});
  useEffect(()=>{void load(); const socket:Socket=io({path:'/socket.io',withCredentials:true}); socket.on('connect',()=>{setConnection('connected');socket.emit('room:subscribe',{roomId,lastSequence:sequence.current});});socket.on('disconnect',()=>setConnection('reconnecting'));socket.on('connect_error',()=>setConnection('reconnecting'));
    const receive=(input:unknown)=>{const outer=ServerEnvelopeSchema.safeParse(input);if(!outer.success)return;const next=RoomSnapshotSchema.safeParse(outer.data.payload);if(!next.success)return;if(sequence.current&&outer.data.sequence>sequence.current+1){void load();return;}if(outer.data.sequence>=sequence.current){sequence.current=outer.data.sequence;setSnapshot(next.data);}};
    for(const event of eventNames)socket.on(event,receive);return()=>{socket.disconnect();};},[roomId,load]);
  const joinUrl=useMemo(()=>snapshot?`${window.location.origin}/join/${snapshot.code}`:'',[snapshot]);
  async function mutate(path:string,method='POST'){setError('');try{await api(path,{method});await load();}catch(e){setError(e instanceof Error?e.message:'Request failed');}}
  async function pairing(){try{const result=await api<{pairingCode:string}>(`/api/rooms/${roomId}/display-pairing-codes`,{method:'POST',body:'{}'});setPairingCode(result.pairingCode);}catch(e){setError(e instanceof Error?e.message:'Could not create pairing code');}}
  if(!snapshot)return <main className="shell"><div className="brand">Watch Bracket</div><div className="card"><h1>Loading lobby…</h1>{error&&<p className="error">{error}</p>}</div></main>;
  const host=snapshot.viewer==='HOST';
  return <main className="shell stack"><div className="brand">Watch Bracket</div>{host&&castDisplay&&<div className="tv-strip"><span><strong>{cast.deviceName} {castDisplay.connected?'connected':'ready to resume'}</strong><br/><small className="muted">Lobby display · {cast.state}</small></span><div className="actions"><button className="secondary" onClick={()=>void cast.requestSession()}>Resume on TV</button><button className="danger" onClick={()=>void cast.disconnect()}>Disconnect</button></div></div>}{error&&<p className="error">{error}</p>}<section className="card"><div className="status"><span className={`dot ${connection==='connected'?'':'off'}`}/>{connection}</div><h1>{snapshot.name}</h1><p className="muted">Room code</p><div className="room-code">{snapshot.code}</div><div className="actions"><button className="secondary" onClick={()=>void navigator.clipboard.writeText(joinUrl)}>Copy join link</button><span>{snapshot.locked?'🔒 Locked':'● Open'}</span></div></section>
    <div className="two-col"><section className="card"><h2>Tonight's crew</h2><ul className="people">{snapshot.participants.map((p,index)=><li className="person" key={p.id??`${p.nickname}-${index}`}><span>{p.connected?'●':'○'} {p.nickname}</span><span>{p.role==='HOST'?'Host':''}</span></li>)}</ul></section><section className="card stack"><h2>Invite people</h2><div style={{background:'white',padding:12,borderRadius:12,width:'fit-content'}}><QRCodeSVG value={joinUrl} size={180}/></div><small className="muted">Scan to join as a guest</small></section></div>
    {host&&<section className="card stack"><h2>Host controls</h2><div className="actions"><button className="secondary" onClick={()=>void mutate(`/api/rooms/${roomId}/${snapshot.locked?'unlock':'lock'}`)}>{snapshot.locked?'Unlock room':'Lock room'}</button><button className="secondary" onClick={pairing}>Pair browser display</button>{cast.launcher}</div>{cast.message&&<p className="muted">{cast.message}</p>}{cast.state==='ready'&&!castDisplay&&<p className="muted">Tap the Cast icon to put this lobby on a supported TV. The phone remains your controller.</p>}{pairingCode&&<p>Enter this on the shared display: <strong className="room-code" style={{fontSize:'2rem'}}>{pairingCode}</strong></p>}{snapshot.displays.filter((display)=>display.kind==='BROWSER').map((display)=><div className="person" key={display.id}><span>{display.connected?'●':'○'} {display.name}</span><button className="danger" onClick={()=>void mutate(`/api/displays/${display.id}`,'DELETE')}>Revoke</button></div>)}</section>}
  </main>;
}
