'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useParams } from 'next/navigation';
import { QRCodeSVG } from 'qrcode.react';
import { io, type Socket } from 'socket.io-client';
import { controllerEvents, RoomSnapshotSchema, ServerEnvelopeSchema, type CatalogItem, type HouseRules, type RoomSnapshot } from '@watch-bracket/realtime-protocol';
import { api } from '../../../lib/api';
import { useCast } from '../../../lib/use-cast';

const presets: Record<HouseRules['preset'], HouseRules> = {
  QUICK_PICK: { preset: 'QUICK_PICK', nominationDurationSeconds: 60, nominationSlots: 2, revealMode: 'AFTER_DEADLINE' },
  MOVIE_NIGHT: { preset: 'MOVIE_NIGHT', nominationDurationSeconds: 120, nominationSlots: 2, revealMode: 'AFTER_DEADLINE' },
  DEEP_DIVE: { preset: 'DEEP_DIVE', nominationDurationSeconds: 180, nominationSlots: 2, revealMode: 'AFTER_DEADLINE' }
};

function useCountdown(deadline: string | null | undefined) {
  const calculate = useCallback(() => deadline ? Math.max(0, Math.ceil((Date.parse(deadline) - Date.now()) / 1000)) : 0, [deadline]);
  const [seconds,setSeconds]=useState(calculate);
  useEffect(()=>{setSeconds(calculate());const timer=setInterval(()=>setSeconds(calculate()),1000);return()=>clearInterval(timer);},[calculate]);
  return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;
}

export default function RoomPage() {
  const { roomId }=useParams<{roomId:string}>(); const [snapshot,setSnapshot]=useState<RoomSnapshot>(); const [connection,setConnection]=useState<'connecting'|'connected'|'reconnecting'>('connecting'); const [error,setError]=useState(''); const [pairingCode,setPairingCode]=useState(''); const [query,setQuery]=useState(''); const [results,setResults]=useState<CatalogItem[]>([]); const [searching,setSearching]=useState(false); const [rules,setRules]=useState<HouseRules>(presets.MOVIE_NIGHT); const sequence=useRef(0);
  const load=useCallback(async()=>{try{const parsed=RoomSnapshotSchema.parse(await api<unknown>(`/api/rooms/${roomId}/snapshot`));sequence.current=parsed.sequence;setSnapshot(parsed);setRules(parsed.rules);setError('');}catch(reason){setError(reason instanceof Error?reason.message:'Could not load room');}},[roomId]);
  const castDisplay=snapshot?.displays.find((display)=>display.kind==='CAST'); const cast=useCast({enabled:snapshot?.viewer==='HOST',roomId,activeDisplay:castDisplay});
  useEffect(()=>{void load();const socket:Socket=io({path:'/socket.io',withCredentials:true});socket.on('connect',()=>{setConnection('connected');socket.emit('room:subscribe',{roomId,lastSequence:sequence.current});});socket.on('disconnect',()=>setConnection('reconnecting'));socket.on('connect_error',()=>setConnection('reconnecting'));
    const receive=(input:unknown)=>{const outer=ServerEnvelopeSchema.safeParse(input);if(!outer.success)return;const next=RoomSnapshotSchema.safeParse(outer.data.payload);if(!next.success)return;if(sequence.current&&outer.data.sequence>sequence.current+1){void load();return;}if(outer.data.sequence>=sequence.current){sequence.current=outer.data.sequence;setSnapshot(next.data);}};
    for(const event of controllerEvents)socket.on(event,receive);return()=>{socket.disconnect();};},[roomId,load]);
  const joinUrl=useMemo(()=>snapshot?`${window.location.origin}/join/${snapshot.code}`:'',[snapshot]); const countdown=useCountdown(snapshot?.nominationDeadline); const host=snapshot?.viewer==='HOST';
  async function mutate(path:string,method='POST',body?:unknown){setError('');try{const init:RequestInit=body===undefined?{method}:{method,body:JSON.stringify(body)};await api(path,init);await load();}catch(reason){setError(reason instanceof Error?reason.message:'Request failed');}}
  async function pairing(){try{const result=await api<{pairingCode:string}>(`/api/rooms/${roomId}/display-pairing-codes`,{method:'POST',body:'{}'});setPairingCode(result.pairingCode);}catch(reason){setError(reason instanceof Error?reason.message:'Could not create pairing code');}}
  async function search(event:React.FormEvent){event.preventDefault();setSearching(true);setError('');try{const response=await api<{items:CatalogItem[]}>(`/api/catalog/search?q=${encodeURIComponent(query)}`);setResults(response.items);}catch(reason){setError(reason instanceof Error?reason.message:'Search failed');}finally{setSearching(false);}}
  if(!snapshot)return <main className="shell"><div className="brand">Watch Bracket</div><div className="card"><h1>Loading room…</h1>{error&&<p className="error">{error}</p>}</div></main>;
  const nominating=snapshot.state==='NOMINATING'; const revealed=snapshot.state==='NOMINATIONS_LOCKED';
  return <main className="shell stack"><div className="brand">Watch Bracket</div>{host&&castDisplay&&<div className="tv-strip"><span><strong>{cast.deviceName} {castDisplay.connected?'connected':'ready to resume'}</strong><br/><small className="muted">Shared display · {cast.state}</small></span><div className="actions"><button className="secondary" onClick={()=>void cast.requestSession()}>Resume on TV</button><button className="danger" onClick={()=>void cast.disconnect()}>Disconnect</button></div></div>}{error&&<p className="error">{error}</p>}
    <section className="card"><div className="status"><span className={`dot ${connection==='connected'?'':'off'}`}/>{connection}</div><h1>{snapshot.name}</h1><p className="muted">Room code</p><div className="room-code">{snapshot.code}</div><div className="actions"><button className="secondary" onClick={()=>void navigator.clipboard.writeText(joinUrl)}>Copy join link</button><span>{snapshot.locked?'🔒 Locked':'● Open'}</span></div></section>
    {snapshot.state==='LOBBY'&&<><div className="two-col"><section className="card"><h2>Tonight&apos;s crew</h2><ul className="people">{snapshot.participants.map((person,index)=><li className="person" key={person.id??`${person.nickname}-${index}`}><span>{person.connected?'●':'○'} {person.nickname}</span><span>{person.role==='HOST'?'Host':''}</span></li>)}</ul></section><section className="card stack"><h2>Invite people</h2><div style={{background:'white',padding:12,borderRadius:12,width:'fit-content'}}><QRCodeSVG value={joinUrl} size={180}/></div><small className="muted">Scan to join as a guest</small></section></div>
      {host&&<section className="card stack"><h2>Start nominations</h2><p className="muted">Everyone privately ranks two titles. The shared display only shows progress until reveal.</p><div className="preset-grid">{Object.values(presets).map((preset)=><button className={rules.preset===preset.preset?'preset selected':'preset secondary'} key={preset.preset} onClick={()=>setRules(preset)}><span><strong>{preset.preset.replaceAll('_',' ')}</strong><br/><small>{preset.nominationDurationSeconds} seconds</small></span></button>)}</div><button onClick={()=>void mutate(`/api/rooms/${roomId}/nominations/start`,'POST',{rules})}>Start nomination timer</button></section>}</>}
    {nominating&&<><section className="card nomination-header"><div><p className="brand">Private nominations</p><h2>{snapshot.nominationProgress.submittedParticipants} of {snapshot.nominationProgress.totalParticipants} have picked</h2><p className="muted">{snapshot.nominationProgress.lockedParticipants} locked in</p></div><div className="timer" aria-label={`${countdown} remaining`}>{countdown}</div></section>
      <section className="card stack"><h2>Your ranked picks</h2>{[1,2].map((rank)=>{const pick=snapshot.ownSubmissions.find((item)=>item.rank===rank);return <div className="ranked-pick" key={rank}><span className="rank">#{rank}</span><span>{pick?<><strong>{pick.title}</strong><br/><small className="muted">{pick.mediaType} · {pick.releaseYear}</small></>:'Choose a title below'}</span></div>})}<div className="actions"><button disabled={snapshot.ownSubmissions.length!==2} onClick={()=>void mutate(`/api/rooms/${roomId}/submissions/${snapshot.viewerReady?'unlock':'lock'}`)}>{snapshot.viewerReady?'Edit picks':'Lock in both picks'}</button></div></section>
      <form className="card stack" onSubmit={search}><h2>Search the mock catalog</h2><label>Title, genre, or description<input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Try science fiction or comedy"/></label><button disabled={searching}>{searching?'Searching…':'Search'}</button>{results.length===0&&query&&<p className="muted">No results yet. Search the deterministic local catalog.</p>}<div className="catalog-results">{results.map((item)=><article className="catalog-item" key={item.catalogKey}><div><strong>{item.title}</strong><br/><small className="muted">{item.mediaType} · {item.releaseYear} · {item.runtimeMinutes} min · {item.genres.join(', ')}</small><p>{item.synopsis}</p></div><div className="actions"><button type="button" className="secondary" onClick={()=>void mutate(`/api/rooms/${roomId}/submissions/1`,'PUT',{catalogKey:item.catalogKey})}>Pick #1</button><button type="button" className="secondary" onClick={()=>void mutate(`/api/rooms/${roomId}/submissions/2`,'PUT',{catalogKey:item.catalogKey})}>Pick #2</button></div></article>)}</div></form>
      {host&&<section className="card stack"><h2>Host timer controls</h2><div className="actions"><button className="secondary" onClick={()=>void mutate(`/api/rooms/${roomId}/nominations/extend`,'POST',{seconds:60})}>Add 1 minute</button><button className="danger" onClick={()=>void mutate(`/api/rooms/${roomId}/nominations/close`)}>Reveal now</button></div></section>}</>}
    {revealed&&<section className="card stack"><p className="brand">Nominations revealed</p><h1>The contenders</h1>{snapshot.candidates.length?<div className="catalog-results">{snapshot.candidates.map((candidate)=><article className="candidate" key={candidate.catalogKey}><span><strong>{candidate.title}</strong><br/><small className="muted">{candidate.mediaType} · {candidate.releaseYear} · best rank #{candidate.bestRank}</small></span><strong>{candidate.supportCount} {candidate.supportCount===1?'supporter':'supporters'}</strong></article>)}</div>:<p>No titles were submitted.</p>}<p className="notice">Tournament play begins in Milestone 4.</p></section>}
    {host&&snapshot.state==='LOBBY'&&<section className="card stack"><h2>Display &amp; room controls</h2><div className="actions"><button className="secondary" onClick={()=>void mutate(`/api/rooms/${roomId}/${snapshot.locked?'unlock':'lock'}`)}>{snapshot.locked?'Unlock room':'Lock room'}</button><button className="secondary" onClick={pairing}>Pair browser display</button>{cast.launcher}</div>{cast.message&&<p className="muted">{cast.message}</p>}{pairingCode&&<p>Enter this on the shared display: <strong className="room-code" style={{fontSize:'2rem'}}>{pairingCode}</strong></p>}{snapshot.displays.filter((display)=>display.kind==='BROWSER').map((display)=><div className="person" key={display.id}><span>{display.connected?'●':'○'} {display.name}</span><button className="danger" onClick={()=>void mutate(`/api/displays/${display.id}`,'DELETE')}>Revoke</button></div>)}</section>}
  </main>;
}
